### ISSUE TITLE
Research the Feasibility of Developing a Custom Dashboard

### ISSUE THREAD

**Issue by yukikazeK** [WangZhen-Ryan/Personal-Finance#35]
** Is your Development Plan with one feature can be break down into several Issue**
Please describe in several issue

** Is your feature request related to a problem? Please describe.
Our project requires a comprehensive and customizable dashboard to present data analytics effectively. The limitations of existing solutions have prompted us to consider the feasibility of developing a custom dashboard tailored to our specific needs.

** Describe the solution you'd like
We need to discuss the feasibility of customizable dashboard in the team meeting, and the team which is responsible for this topic should explores the technical and resource requirements for developing a custom dashboard from scratch.

**Comment by WangZhen-Ryan** [comment]
Clone to Discussions. Closed.
